export const gigs = [
	{
		date: '10/10/20',
		location: `The Ol' Bar`,
		lineup: ['Gerry McKeveny', 'Quarter Horse', 'Neil Young'],
		time: '7:00pm-9:00pm',
		address: '1234 bar street, NY',
	},
	{
		date: '10/10/20',
		location: `The Ol' Bar`,
		lineup: ['Gerry McKeveny', 'Quarter Horse', 'Neil Young'],
		time: '7:00pm-9:00pm',
		address: '1234 bar street, NY',
	},
	{
		date: '10/10/20',
		location: `The Ol' Bar`,
		lineup: ['Gerry McKeveny', 'Quarter Horse', 'Neil Young'],
		time: '7:00pm-9:00pm',
		address: '1234 bar street, NY',
	},
	{
		date: '10/10/20',
		location: `The Ol' Bar`,
		lineup: ['Gerry McKeveny', 'Quarter Horse', 'Neil Young'],
		time: '7:00pm-9:00pm',
		address: '1234 bar street, NY',
	},
	{
		date: '10/10/20',
		location: `The Ol' Bar`,
		lineup: ['Gerry McKeveny', 'Quarter Horse', 'Neil Young'],
		time: '7:00pm-9:00pm',
		address: '1234 bar street, NY',
	},
	{
		date: '10/10/20',
		location: `The Ol' Bar`,
		lineup: ['Gerry McKeveny', 'Quarter Horse', 'Neil Young'],
		time: '7:00pm-9:00pm',
		address: '1234 bar street, NY',
	},
	{
		date: '10/10/20',
		location: `The Ol' Bar`,
		lineup: ['Gerry McKeveny', 'Quarter Horse', 'Neil Young'],
		time: '7:00pm-9:00pm',
		address: '1234 bar street, NY',
	},
	{
		date: '10/10/20',
		location: `The Ol' Bar`,
		lineup: ['Gerry McKeveny', 'Quarter Horse', 'Neil Young'],
		time: '7:00pm-9:00pm',
		address: '1234 bar street, NY',
	},
	{
		date: '10/10/20',
		location: `The Ol' Bar`,
		lineup: ['Gerry McKeveny', 'Quarter Horse', 'Neil Young'],
		time: '7:00pm-9:00pm',
		address: '1234 bar street, NY',
	},
];
